#!/usr/bin/env bash
# This script installs and configures HAProxy load balancer

apt-get update
apt-get install -y haproxy

cat <<EOF > /etc/haproxy/haproxy.cfg
global
    daemon

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 34.203.218.185:80 check
    server web-02 44.202.164.145:80 check
EOF

service haproxy restart
