#!/usr/bin/env bash
# Install and configure nginx on Ubuntu

# Update package list
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create custom page
echo "Holberton School for the win!" > /var/www/html/index.html

# Ensure nginx is running (NOT systemctl)
service nginx restart
