#!/usr/bin/env bash
# Configure Nginx with a custom 404 page

# Install nginx
apt-get -y update
apt-get -y install nginx

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure nginx to use the custom 404 page
sed -i '/server_name _;/a \
    error_page 404 /404.html;\n\
    location = /404.html {\n\
        internal;\n\
    }' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
